import time

import requests
from geopy.geocoders import Nominatim
import datetime as dt
import smtplib


my_email = "automationqatesting65@gmail.com"
password = "mvyq lcah icwj tpbz"
to_email = "automationqatesting65@yahoo.com"
subject = "Look Up!"
body= "ISS is overhead and it is nightime."

def send_email():
    with smtplib.SMTP("smtp.gmail.com") as connection:  # email provider @gmail com | smtp.mail.yahoo.com
        connection.starttls()  # Transport Layer Security - encrypt messages
        connection.login(user=my_email, password=password)
        connection.sendmail(from_addr=my_email,
                            to_addrs=to_email,
                            msg=f"Subject:{subject}\n\n{body}")

geolocator = Nominatim(user_agent="ISS Location")

MY_LAT = 53.801277
MY_LNG = -1.548567
#Leeds coordinates
params = {
    "lat": MY_LAT,
    "lng": MY_LNG,
    "formatted":0

}
response_sun = requests.get(url="https://api.sunrise-sunset.org/json",
                        params=params)
response_sun.raise_for_status()

data= response_sun.json()
sunrise = int(data["results"]["sunrise"].split("T")[1].split(":")[0])
sunset = int(data["results"]["sunset"].split("T")[1].split(":")[0])
print(f"Sunrise: {sunrise}, Sunset: {sunset}")

time_now = dt.datetime.now()
print(time_now.hour)

def is_iss_overhead():
    # call ISS api to check current latitude and longitude and compare with the one generated by a third party to check
    # if error margin is less than 5
    response = requests.get(url="http://api.open-notify.org/iss-now.json")
    response.raise_for_status()
    body = response.json()
    print(body)
    iss_longitude = float(body["iss_position"]["longitude"])
    iss_latitude = float(body["iss_position"]["latitude"])
    print(iss_longitude, iss_latitude)
    position = (body['iss_position']['latitude'], body['iss_position']['longitude'])
    location = geolocator.reverse((MY_LAT,MY_LNG))
    print(location.address)
    if MY_LAT-5 <= iss_latitude <= MY_LAT+5 and MY_LNG <= iss_longitude <= MY_LNG+5:
        return True
    else:
        return False

def is_night():
    if time_now.hour >= sunset or time_now.hour <= sunrise:
        return True
    else:
        return False

while True:
    time.sleep(240)
    if is_iss_overhead() and is_night():
        print("look UP!!")
        #Send an email to look up
        send_email()

